"""Support code for week2.ipynb.

The notebook walks through building eFlesh's touch pad. This module holds the
parts that would be busywork to type out: reading eFlesh's cell pattern and
material table, turning struts into a surface, and drawing the result.

Learners do not edit this file. It is imported by the notebook, never run.

Everything is in millimetres, with Z pointing up.
"""

from __future__ import annotations

from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np

__all__ = [
    "find_repo_root",
    "output_dir",
    "load_material_model",
    "read_cell_pattern",
    "inflate_lattice",
    "drop_debris",
    "describe_mesh",
    "plot_section",
    "slicer_notes",
]

CELL_PATTERN = (
    "eFlesh/microstructure/microstructure_inflators/"
    "data/patterns/3D/reference_wires/pattern0646.wire"
)
MATERIAL_TABLE = "eFlesh/microstructure/matopt/tools/material2geometry"


# -- paths -----------------------------------------------------------------
def find_repo_root(start: Path | None = None) -> Path:
    """Walk up from the current folder until the project root."""
    start = (start or Path.cwd()).resolve()
    for folder in (start, *start.parents):
        if (folder / "eFlesh" / "generate_lattice_v10_5.py").exists():
            return folder
    raise FileNotFoundError("Open Jupyter from inside the project folder.")


def output_dir() -> Path:
    """Where the notebook saves its files. Created on first use."""
    path = Path(__file__).resolve().parent / "output"
    path.mkdir(parents=True, exist_ok=True)
    return path


# -- eFlesh's material table -----------------------------------------------
class MaterialModel:
    """Turns a target softness into strut thicknesses.

    Wraps eFlesh's `material2geometry`, a lookup table fitted to real test
    results. Pure Python, so unlike the lattice generator it runs anywhere.
    """

    def __init__(self, inner):
        self._inner = inner

    def thicknesses(self, softness: float, poisson: float = 0.09):
        """The four strut thicknesses for this softness, as a fraction of a cell.

        Multiply by the cell size to get millimetres.
        """
        return list(self._inner.evaluate(poisson, softness)[5:9])

    def all_parameters(self, softness: float, poisson: float = 0.09):
        """All 13 shape parameters, as eFlesh's generator uses them."""
        return list(self._inner.evaluate(poisson, softness))


def load_material_model(repo_root: Path) -> MaterialModel:
    """Load eFlesh's softness-to-thickness table."""
    import contextlib
    import io
    import sys

    tools = Path(repo_root) / MATERIAL_TABLE
    coefficients = tools / "0646_geo_1_coeffs.txt"
    if not coefficients.exists():
        raise FileNotFoundError(f"material table not found at {coefficients}")

    if str(tools) not in sys.path:
        sys.path.insert(0, str(tools))
    from material2geometry import Material2Geometry

    # The constructor prints diagnostics; keep the notebook output clean.
    with contextlib.redirect_stdout(io.StringIO()):
        return MaterialModel(Material2Geometry(in_path=str(coefficients)))


# -- eFlesh's cell pattern -------------------------------------------------
def read_cell_pattern(repo_root: Path):
    """Read pattern0646: the skeleton of one lattice cell.

    A plain list of points and lines in cell coordinates, where the cell runs
    from -0.5 to 0.5 on each axis. This is the same file eFlesh's generator
    hands to its C++ lattice builder.

    Returns (points, lines).
    """
    path = Path(repo_root) / CELL_PATTERN
    if not path.exists():
        raise FileNotFoundError(f"cell pattern not found at {path}")

    points, lines = [], []
    for row in path.read_text().splitlines():
        parts = row.split()
        if not parts:
            continue
        if parts[0] == "v":
            points.append([float(value) for value in parts[1:4]])
        elif parts[0] == "l":                      # the file counts from 1
            lines.append((int(parts[1]) - 1, int(parts[2]) - 1))
    return np.asarray(points, dtype=float), np.asarray(lines, dtype=int)


def _struts(repo_root, cell_size, first_cell, last_cell) -> np.ndarray:
    """Copy the cell pattern into every cell. Returns strut end points."""
    points, lines = read_cell_pattern(repo_root)
    struts = []
    for i in range(int(first_cell[0]), int(last_cell[0]) + 1):
        for j in range(int(first_cell[1]), int(last_cell[1]) + 1):
            for k in range(int(first_cell[2]), int(last_cell[2]) + 1):
                middle = (np.array([i, j, k], dtype=float) + 0.5) * cell_size
                placed = points * cell_size + middle
                for a, b in lines:
                    struts.append((placed[a], placed[b]))
    return np.asarray(struts, dtype=float)


# -- turning struts into a surface -----------------------------------------
def _distance_field(struts, axes, radius):
    """Distance to the nearest strut, negative inside one."""
    xs, ys, zs = axes
    field = np.full((xs.size, ys.size, zs.size), 1e3, dtype=np.float32)
    margin = radius + float(max(np.diff(xs)[0], np.diff(ys)[0], np.diff(zs)[0]))

    for start, end in struts:
        low, high = np.minimum(start, end) - margin, np.maximum(start, end) + margin
        window = []
        for values, lo, hi in zip(axes, low, high):
            i0 = int(np.searchsorted(values, lo))
            i1 = int(np.searchsorted(values, hi)) + 1
            window.append(slice(max(i0, 0), min(i1, values.size)))
        if any(w.start >= w.stop for w in window):
            continue

        gx = xs[window[0]][:, None, None]
        gy = ys[window[1]][None, :, None]
        gz = zs[window[2]][None, None, :]
        along = end - start
        length_sq = float(along @ along)
        if length_sq == 0.0:
            continue
        px, py, pz = gx - start[0], gy - start[1], gz - start[2]
        t = np.clip((px * along[0] + py * along[1] + pz * along[2]) / length_sq, 0.0, 1.0)
        dx, dy, dz = px - t * along[0], py - t * along[1], pz - t * along[2]
        distance = np.sqrt(dx * dx + dy * dy + dz * dz) - radius

        block = field[tuple(window)]
        np.minimum(block, distance.astype(np.float32), out=block)

    return field


def inflate_lattice(repo_root, size, start, cell_size, strut_radius,
                    first_cell, last_cell, step: float = 0.18):
    """Fill a box with lattice and return it as a mesh.

    eFlesh does this with a C++ program that only builds on Linux. This is the
    Python stand-in. It uses eFlesh's real cell pattern and the real cell size,
    thickens every strut to `strut_radius`, trims the result to the box, and
    converts it to triangles.

    What it does not copy: eFlesh gives each strut one of four thicknesses and
    rounds off the joints. Both live in the C++ program.

    `start` is the box's lowest corner, which is where the grid shift lives.
    """
    if None in (size, start, cell_size, strut_radius):
        raise ValueError("inflate_lattice: fill in size, start, cell_size and strut_radius.")

    import trimesh
    from skimage import measure

    start = np.asarray(start, dtype=float)
    size = np.asarray(size, dtype=float)
    pad = 1.0
    # The half-step offset keeps the box faces off the sample points. A surface
    # landing exactly on a sample point produces broken triangles.
    axes = tuple(
        np.arange(origin - pad + step / 2.0, origin + length + pad, step, dtype=np.float32)
        for origin, length in zip(start, size)
    )

    field = _distance_field(
        _struts(repo_root, cell_size, first_cell, last_cell), axes, strut_radius
    )

    grids = np.meshgrid(*axes, indexing="ij")
    box_field = np.maximum.reduce([
        np.maximum(-(g - origin), (g - origin) - length)
        for g, origin, length in zip(grids, start, size)
    ])
    field = np.maximum(field, box_field.astype(np.float32))

    points, faces, _, _ = measure.marching_cubes(field, level=0.0, spacing=(step,) * 3)
    points = points + np.array([axis[0] for axis in axes])

    mesh = trimesh.Trimesh(vertices=points, faces=faces, process=True)
    mesh.fix_normals()
    return mesh


def drop_debris(mesh, max_faces: int = 1000, keep_near=(), keep_radius: float = 5.0):
    """Delete small disconnected fragments.

    `keep_near` protects pieces close to a given (x, y). A magnet pocket wall is
    its own small closed piece, so without this it gets deleted along with the
    rubbish -- which is exactly what went wrong in an earlier version of eFlesh,
    sealing all four pockets with no error.
    """
    import trimesh

    pieces = mesh.split(only_watertight=False)
    if len(pieces) <= 1:
        return mesh

    def protected(piece) -> bool:
        if not keep_near:
            return False
        cx, cy = piece.vertices[:, 0].mean(), piece.vertices[:, 1].mean()
        return any((cx - px) ** 2 + (cy - py) ** 2 < keep_radius ** 2 for px, py in keep_near)

    kept = [p for p in pieces if len(p.faces) > max_faces or protected(p)]
    if not kept or len(kept) == len(pieces):
        return mesh
    print(f"  removed {len(pieces) - len(kept)} small fragment(s)")
    return trimesh.util.concatenate(kept)


# -- reporting -------------------------------------------------------------
def describe_mesh(mesh, label: str = "mesh") -> None:
    size = mesh.bounding_box.extents
    print(f"{label}: {len(mesh.faces):,} triangles, watertight = {mesh.is_watertight}")
    print(f"  size   {size[0]:.2f} x {size[1]:.2f} x {size[2]:.2f} mm")
    print(f"  solid  {mesh.volume:,.0f} mm3 "
          f"({100 * mesh.volume / float(np.prod(size)):.0f}% of the box)")


def plot_section(mesh, y: float, title: str = "") -> None:
    """Draw a vertical slice through the part at depth `y`."""
    cut = mesh.section(plane_origin=[0.0, y, 0.0], plane_normal=[0.0, 1.0, 0.0])
    if cut is None:
        raise ValueError(f"nothing to cut at y = {y} mm")

    _, ax = plt.subplots(figsize=(10, 5))
    for piece in cut.discrete:
        ax.plot(piece[:, 0], piece[:, 2], color="tab:blue", lw=0.9)
    ax.set(
        title=title or f"Cut at y = {y:.1f} mm",
        xlabel="x (mm)",
        ylabel="height (mm)",
        xlim=(-1, 31),
        ylim=(-1, 15),
    )
    ax.set_aspect("equal")
    plt.show()


def slicer_notes(magnet_height: float, base: float, poles: str, spots,
                 layer: float = 0.20, first_layer: float = 0.25) -> str:
    """Printer settings, including which layer to pause on."""
    pause_at = base + magnet_height
    layer_number = int((pause_at - first_layer) / layer + 1)
    actual = first_layer + (layer_number - 1) * layer
    listed = "\n".join(
        f"    {n}. x = {x:.1f} mm, y = {y:.1f} mm, pole {pole}"
        for n, ((x, y), pole) in enumerate(zip(spots, poles.split()), start=1)
    )
    return f"""PRINTER SETTINGS
  Material       TPU 95A
  Nozzle         0.4 mm
  Layer height   {layer} mm (first layer {first_layer} mm)
  Speed          20 mm/s
  Bed / nozzle   45 C / 220-230 C
  Brim 10 mm, no supports

  PAUSE AT LAYER {layer_number}   (printed height {actual:.2f} mm)
  The pockets are open at this point. Drop the magnets in, then resume.
  The next 1 mm of printing seals them in.

  Magnets: 4 x N52, 4.8 mm across, 1.6 mm thick
{listed}
"""
